[tool.poetry]
name = "pubsub"
version = "0.0.0"
description = ""
authors = ["Thomas Weatherston <thomas.weatherston@atheon.co.uk>"]

[tool.poetry.dependencies]
python = "^3.8"
kombu = ">= 4, < 6"
celery = ">= 4, < 6"

Flask = { version = "^2", optional = true}
Django = { version = "^4", optional = true}

[tool.poetry.dev-dependencies]
pytest = "^6"
black = "^21.12b0"
pytest-cov = "^3"

[tool.poetry.extras]
flask = ["Flask"]
django = ["Django"]

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning"]
build-backend = "poetry.core.masonry.api"

[tool.poetry-dynamic-versioning]
enable = true

[tool.tox]
legacy_tox_ini = """
[tox]
isolated_build = True
envlist = py36,py37, py38, py39, py310

[tox:.package]
basepython = python3

[gh-actions]
python =
    3.6: py36
    3.7: py37
    3.8: py38
    3.9: py39
    3.10: py310

[testenv]
deps =
    pytest
    pytest-cov
commands = pytest
"""